---
- name: Manage Files
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
  - name: Manage etc motd
    lineinfile:
      path: "/etc/motd"
      regexp: "^This machine is managed by SysEng"
      line: "This machine is managed by DevOps"