---
- name: R1soft Agent Installation
  hosts: all
  become: true
  become_method: sudo
  user: centos
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  tasks:
  - name: Create repo
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/

  - name: Install agent
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    package:  
      name: serverbackup-enterprise-agent   
      state: installed 
    notify: AGENT_RESTART

  - name: Stop iptables
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    service: 
      name: iptables
      state: stopped
      enabled: false

  - name: Get Key
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
    shell: "r1soft-setup --get-key http://18.132.14.237/" 

  
  handlers: 
  - name: AGENT_RESTART
    service: 
      name: cdp-agent 
      state: restarted
      enabled: true