---
- name: R1soft Agent Installation
  hosts: all
  become: true
  become_method: sudo
  user: centos
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == '7')
  tasks:
  - name: Create repo
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/


  - name: Install agent
    package:
      name: serverbackup-enterprise-agent
      state: installed
    notify: AGENT_RESTART

  - name: Start agent
    service:
      name: cdp-agent
      state: restarted
      enabled: true


  - name: Stop iptables
    service:
      name: iptables
      state: stopped
      enabled: false


  - name: Get Key
    shell: "r1soft-setup --get-key http://backup.http://35.177.252.228/"



  handlers:
    name: AGENT_RESTART
    service:
      name: cdp-agent
      state: restarted
      enabled: true
