---
- name: Stop Services
  hosts: all #DB
  become: true
  become_method: sudo
  user: centos
  ignore_errors: true      #Do not stop if there are errors
  tasks:


  - name: Stop r1soft
    when: (ansible_distibution == "CentOS" and ansible_distibution_major_version == "7")
    systemd:
      name: sbm-agent
      state: stopped
    ignore_errors: true


 - name: Stop r1soft on CentOS 6
    when: (ansible_distibution == "CentOS" and ansible_distibution_major_version == "6")
    service:
      name: cdp-server
      state: stopped
    ignore_errors: true

  - name: Stop Filebeat
    when: (ansible_distibution == "CentOS" and ansible_distibution_major_version == "7")
      name: filebeat
      state: stopped
    ignore_errors: true

    - name: Stop NRPE
    when: (ansible_distibution == "CentOS" and ansible_distibution_major_version == "7")
      name: nrpe
      state: stopped
    ignore_errors: true
  

  - name: Stop Mariadb
    when: (ansible_distibution == "CentOS" and ansible_distibution_major_version == "7")
      name: mariadb
      state: stopped
    ignore_errors: true