---
- name: Installs wordpress
  hosts: 34.220.140.185
  become: yes
  become_method: sudo
  tasks:
    - name: Install necessary packages
      package:
        name: "{{item}}"
        state: latest
      with_items:
       - epel-release
       - wget 
       - unzip
       - mariadb-server
      ignore_errors: true

  
    - name: Install epel-release
      shell: "sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y"
    - name: config manager enabled 
      shell: "sudo yum-config-manager --enable remi-php72"
    - name : update httpd PHP 
      shell: "sudo yum install httpd php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql mysql -y" 


    - name: Download wordpress Package
      get_url:
        url: https://wordpress.org/wordpress-5.2.1.tar.gz
        dest: /tmp/

    - name: Unzip wordpres file
      unarchive:
        src: "/tmp/wordpress-5.2.1.tar.gz"    
        dest: "/var/www/html"
        remote_src: yes
      become: yes
      become_method: sudo

    - name: Move files to html folder
      shell: "mv /var/www/html/wordpress/* /var/www/html"
      become: yes
      become_method: sudo
      ignore_errors: yes

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted  
        enabled: yes
      become: yes
      become_method: sudo
    - name: Create route53 entry
       hosts: localhost
       tasks:
    - name: Route53 a record
      route53:
        state: "present"
        zone: "devoploadbalancer.com"
        record: "wordpress.devoploadbalancer.com"
        type: A
        ttl: 7200
        value: "34.220.140.185" #change Ip