---
- name: Installs wordpress
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Install necessary packages
      package:
        name: “{{item}}”
        state: latest
      with_items:
       - epel-release
       - wget
       - unzip
       - mariadb-server
      ignore_errors: true
      notify: MARIADB RESTART

    - name: Install epel-release
      shell: “sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y”
    - name: config manager enabled
      shell: “sudo yum-config-manager --enable remi-php72”
    - name : update httpd PHP
      shell: “sudo yum install httpd php php-common php-opcache php-mcrypt php-cli php-gd php-curl php-mysql mysql -y”
    - name: Download wordpress Package
      get_url:
        url: https://wordpress.org/wordpress-{{WORDPRESS_VERSION}}.tar.gz
        dest: /tmp/

    - name: Unzip wordpres file
      unarchive:
        src: “/tmp/wordpress-5.2.1.tar.gz”
        dest: “/var/www/html”
        remote_src: yes
      become: yes
      become_method: sudo
    - name: Move files to html folder
      shell: “mv /var/www/html/wordpress/* /var/www/html”
      become: yes
      become_method: sudo
      ignore_errors: yes
    
    - name: Create 1 user bob
      user:
        name: bob
        generate_ssh_key: yes
    - name: Create 1 user Ben
      user:
        name: Ben
        generate_ssh_key: yes
    - name: Create 1 user ben
      user:
        name: ben
        generate_ssh_key: yes
    - name: Create 1 user lisa
      user:
        name: lisa
        generate_ssh_key: yes
    - name: Create 1 user katty
      user: 
        name: katty
        generate_ssh_key: yes
    - name: Route53 a record
      route53:
        state: “present”
        zone: “devoploadbalancer.com.”
        record: “wordpress.com”
        type: A
        ttl: 172800
        value: “35.177.7.126”