---
- name: Zips logs over 90 days old
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks:
  - name: Run find command
    shell: 'find /var/log -type f -name "*.log" -size +100 -exec gzip -v9 {} +'